"""empty message

Revision ID: 324dba8f979d
Revises: 
Create Date: 2021-10-06 02:37:10.658009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324dba8f979d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('pw', sa.BINARY(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
